---
- hosts: all
  tasks:
  - name: Debug remote ansible env
    debug:
      msg: "{{ ansible_env }}"

  - name: Debug hostvars
    debug:
      var: hostvars[inventory_hostname]

  - name: Debug local ansible inventory_id
    debug:
      var: hostvars[inventory_hostname]['tower_inventory_id']
