---
- hosts: all
  tasks:
  - name: Debug remote ansible env
    debug:
      msg: "{{ ansible_env }}"

  - name: Debug local ansible env
    debug:
      msg: "{{ ansible_env }}"
      delegate_to: localhost

  - name: Debug local ansible inventory_id
    debug:
      msg: "{{ ansible_env.INVENTORY_ID }}"
      delegate_to: localhost
