---
- hosts: all
  tasks:
  - name: Debug remote ansible env
    debug:
      msg: "{{ ansible_env }}"

  - name: Debug local ansible env
    local_action:
      module: debug
      msg: "{{ ansible_env }}"

  - name: Debug local ansible inventory_id
    local_action:
      module: debug
      msg: "{{ ansible_env.INVENTORY_ID }}"
